services:
  - type: web
    name: menag-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: menag-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
